### ISSUE TITLE
Zmodem tests 6,7,8,9

### ISSUE THREAD

**Issue by mbains** [klamonte/jermit#2]
Hi @klamonte 
TestAll.java references 
```
            System.setProperty("jermit.zmodem.escapeControlChars", "true");
            (new Zmodem6()).doTest();
            (new Zmodem7()).doTest();
            System.setProperty("jermit.zmodem.escapeControlChars", "false");

            /*
             * Noisy tests.
             */
            (new Zmodem8()).doTest();
            (new Zmodem9()).doTest();
```

https://github.com/klamonte/jermit/blob/master/src/jermit/tests/TestAll.java#L148

But those are not checked into the zmodem test directory. https://github.com/klamonte/jermit/tree/master/src/jermit/tests/zmodem

**Comment by klamonte** [comment]
Sorry to be so late getting here, I moved across states and took a new job.

These tests are not yet ready, they are leftovers from copying Kermit tests.  I will get this cleaned up soon.

In the meantime jermit has moved to gitlab:  https://gitlab.com/klamonte/jermit
